### GET example.com
GET http://www.example.com/

### GET JSON placeholder
GET https://jsonplaceholder.typicode.com/posts

### GET one post
GET https://jsonplaceholder.typicode.com/posts/2

### DELETE one post
DELETE https://jsonplaceholder.typicode.com/posts/2

### POST create one post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "New post!",
    "body": "This is my post!"
}

### PUT update one post - need to send ALL other data
PUT https://jsonplaceholder.typicode.com/posts/2
Content-Type: application/json

{
    "title": "New post!",
    "body": "...",
    "userid": 4
}

### PATCH partial update
PATCH https://jsonplaceholder.typicode.com/posts/3
Content-Type: application/json

{
    "title": "New post!"
}