### GET 
GET http://localhost:3000/api/cards

### GET id
GET http://localhost:3000/api/cards/1234abc123


### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "What is Node.js?",
    "author": "Max Mustermann"
}

### PUT
PUT http://localhost:3000/api/cards/1234
Content-Type: application/json

{
    "text": "This is a post request"
}

### PATCH
PATCH http://localhost:3000/api/cards/1234
Content-Type: application/json

{
    "text": "This is a post request"
}

### DELETE
DELETE  http://localhost:3000/api/cards/1234
