### GET 
GET http://localhost:4000/api/cards

### GET id
GET http://localhost:4000/api/cards/61543c4aff5980e4d2ea74c4


### POST
POST http://localhost:4000/api/cards
Content-Type: application/json

{
    "text": "Uhhu no version key!",
    "author": "Max Mustermann"
}

### PUT
PUT http://localhost:4000/api/cards/1234abc
Content-Type: application/json

{
    "text": "This is a post request",
    "author": "John Doe"
}

### PATCH
PATCH http://localhost:4000/api/cards/615474b0fa795ff829738555
Content-Type: application/json

{
    "author": "Max"
}

### DELETE
DELETE  http://localhost:4000/api/cards/615474d520eb1d573837ec76
